name: Build HTML CMake Application

on:
  pull_request:
    branches:
      - samsung_wasm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Show Branch SHA
      run: echo ${{ github.event.pull_request.head.sha }}

    - name: Build Docker Image
      run: docker build -t moonlight-tizen \
          --build-arg PR_COMMIT_SHA=${{ github.event.pull_request.head.sha }} .

    # - name: Run Docker Container
    #   run: docker run --rm html-cmake-app

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-artifacts
        path: build/widget/  # Replace this with the actual path

