name: Build HTML CMake Application

on:
  pull_request:
    branches:
      - samsung_wasm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }} # Checkout the PR branch commit

    - name: Create Archive
      run: |
        mkdir -p app
        mv * app/ || true
        zip -r app.zip app

    - name: Build Docker Image
      run: |
        cd app
        docker build -t moonlight-tizen --build-arg APP_ARCHIVE=app.zip .

    - name: Create and Copy Artifacts
      run: |
        mkdir -p artifacts
        docker run --rm -v $(pwd)/artifacts:/build/widget moonlight-tizen

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-artifacts
        path: artifacts  # Upload the artifacts directory

